# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb971d5da31613819790296f5ff6147c0a97cd6a764e5ed2c2871c191071773405167919ac53b4070e63c0c4ca86dd55811cb332119889b5ee08ab9da1e7651

test:
  secret_key_base: 40d3da41739e60fac09750c606c6ca38b6936a7d36c2ce4f1d8e00dcafd85c0fcf624d2e488f015273f048274a04760c3aa29f746daf13d98e19041a9aede5f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
